name: Build-Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "tag: git tag you want create. (sample 1.0.0)"
        required: true
      dry-run:
        description: "dry-run: true will never create release/nuget."
        required: true
        default: "false"

env:
  GIT_TAG: ${{ inputs.tag }}
  DRY_RUN: ${{ inputs.dry-run }}

jobs:
  # dotnet
  build-dotnet:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - uses: Cysharp/Actions/.github/actions/setup-dotnet@main
        with:
          dotnet-version: |
            6.0.x
            7.0.x
          include-prerelease: "true"
      # pack nuget
      - run: dotnet build -c Release -p:Version=${{ env.GIT_TAG }}
      - run: dotnet test -c Release --no-build
      - run: dotnet pack -c Release --no-build -p:Version=${{ env.GIT_TAG }} -o ./publish
      - uses: actions/upload-artifact@v2
        with:
          name: nuget
          path: ./publish

  # unity
  update-packagejson:
    uses: Cysharp/Actions/.github/workflows/update-packagejson.yaml@main
    with:
      file-path: ./src/MemoryPack.Unity/Assets/Plugins/MemoryPack/package.json
      tag: ${{ inputs.tag }}
      dry-run: ${{ fromJson(inputs.dry-run) }}

  build-unity:
    needs: [update-packagejson]
    strategy:
      matrix:
        unity: ["2021.3.11f1"]
        include:
          - unity: 2021.3.11f1
            license: UNITY_LICENSE_2021
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - run: echo ${{ needs.update-packagejson.outputs.sha }}
      - uses: actions/checkout@v3
        with:
          ref: ${{ needs.update-packagejson.outputs.sha }}
      # Execute scripts: Export Package
      # /opt/Unity/Editor/Unity -quit -batchmode -nographics -silent-crashes -logFile -projectPath . -executeMethod PackageExporter.Export
      - name: Export unitypackage
        uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets[matrix.license] }}
        with:
          projectPath: src/MemoryPack.Unity
          unityVersion: ${{ matrix.unity }}
          targetPlatform: StandaloneLinux64
          buildMethod: PackageExporter.Export
          versioning: None
      # check meta files
      - uses: Cysharp/Actions/.github/actions/check-metas@main
        with:
          directory: src/MemoryPack.Unity
      # Store artifacts.
      - uses: actions/upload-artifact@v2
        with:
          name: MemoryPack.Unity.${{ env.GIT_TAG }}.unitypackage
          path: ./src/MemoryPack.Unity/MemoryPack.${{ env.GIT_TAG }}.unitypackage
          if-no-files-found: error

  # release
  create-release:
    needs: [update-packagejson, build-dotnet, build-unity]
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      # setup dotnet for nuget push
      - uses: Cysharp/Actions/.github/actions/setup-dotnet@main
        with:
          dotnet-version: |
            6.0.x
            7.0.x
          include-prerelease: "true"
      # Download (All) Artifacts to current directory
      - uses: actions/download-artifact@v2
      - run: ls -lR
      # Create Releases
      - uses: actions/create-release@v1
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.GIT_TAG }}
          release_name: Ver.${{ env.GIT_TAG }}
          draft: true
          prerelease: false
        if: inputs.dry-run == 'false'
      # Upload to NuGet
      - run: dotnet nuget push "./nuget/*.nupkg" -s https://www.nuget.org/api/v2/package -k ${{ secrets.NUGET_KEY }}
        if: inputs.dry-run == 'false'
      # Upload to Releases(unitypackage)
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./MemoryPack.Unity.${{ env.GIT_TAG }}.unitypackage/MemoryPack.Unity.${{ env.GIT_TAG }}.unitypackage
          asset_name: MemoryPack.Unity.${{ env.GIT_TAG }}.unitypackage
          asset_content_type: application/octet-stream
        if: inputs.dry-run == 'false'

  cleanup:
    if: needs.update-packagejson.outputs.is-branch-created == 'true'
    needs: [update-packagejson, build-unity]
    uses: Cysharp/Actions/.github/workflows/clean-packagejson-branch.yaml@main
    with:
      branch: ${{ needs.update-packagejson.outputs.branch-name }}
